### ISSUE TITLE
Success: gitlab-ci-multi-runner testing on gitlab-ci-multi-runner

### ISSUE THREAD

**Issue by kingcody** [ayufan/gitlab-ci-multi-runner#20]
So not a major feat, but I still thought it'd be fun to share :smile: 

## The runner (gitlab-ci-multi-runner)
![screen shot 2015-04-02 at 07 17 26](https://cloud.githubusercontent.com/assets/2544108/6963380/af2c2150-d90c-11e4-9c16-3d632a94bcc0.png)

## Runner's config
```toml
[[runners]]
  name = "Gitlab-CI Multi-Runner Tester"
  url = "https://ci.digitallyseamless.com/"
  token = "XXXXXXXXXXXXXXXXXXXXXXXX"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  shell = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "golang:dsca"
    privileged = false
    disable_cache = false
    disable_pull = false
    volumes = ["/cache"]
    cache_dir = ""
    registry = ""
```

## The job
![screen shot 2015-04-02 at 07 40 49](https://cloud.githubusercontent.com/assets/2544108/6963405/04bf642e-d90d-11e4-9f11-3ae447f38f96.png)
 
## The build
![screen shot 2015-04-02 at 07 40 14](https://cloud.githubusercontent.com/assets/2544108/6963415/1e496db8-d90d-11e4-8da5-9057f9c84d7f.png)

Yay!!!
